### ISSUE TITLE
Hide ugly (and apparently useless) scrollbars?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#159]
![screenshot from 2017-06-15 11-21-32](https://user-images.githubusercontent.com/546692/27174572-ecde6f28-51bc-11e7-929f-fdc04d416fc4.png)

(On Fx Nightly on Linux)

**Comment by magopian** [comment]
PR #164 should fix that ;)

**Comment by magopian** [comment]
Should now be fixed: https://mozilla-services.github.io/buildhub/searchkit/

If not, please reopen!

**Comment by leplatrem** [comment]
I still have a scrollbar at the right side of the tabs panel:
![screenshot from 2017-06-20 12-27-45](https://user-images.githubusercontent.com/546692/27328992-49abee06-55b4-11e7-8faf-f9b5dc195c18.png)

**Comment by magopian** [comment]
Can't find a way to reproduce that :'( Do you have special settings for your DPI or your zoom or something?
